steps:
  - name: "gcr.io/cloud-builders/go"
    args: ["install", "github.com/kakarot1994/test"]
    env: ["PROJECT_ROOT=github.com/kakarot1994/test"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/boreal-complex-237604/test:$TAG_NAME", "-f", "Dockerfile", "."]
images:
  - "gcr.io/boreal-complex-237604/test:$TAG_NAME"
